name: CI/CD Pipeline for FooApp

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/fooapp:${{ github.sha }} .

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHRC_TOKEN }}

      - name: Push Docker image to Docker Hub
        run: docker push ghcr.io/${{ github.repository_owner }}/fooapp:${{ github.sha }}

