name: CI/CD Pipeline for FooApp

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/fooapp:${{ github.sha }} .

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHRC_TOKEN }}

      - name: Push Image to GHCR
        run: docker push ghcr.io/${{ github.repository_owner }}/fooapp:${{ github.sha }}

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USERNAME }}
          key: ${{ secrets.HOST_KEY }}
          script: |
            docker pull ghcr.io/${{ github.repository_owner }}/fooapp:${{ github.sha }}
            docker stop fooapp || true
            docker rm fooapp || true
            docker run -d --name fooapp -p 5000:5000 ghcr.io/${{ github.repository_owner }}/fooapp/${{ github.sha }}

